- [ ] tests!!!
- [ ] alternative auto refresh where only currently open file is looked at so that you could edit events in realtime, still refresh fully on reopen
- [ ] settings, allow disabling the automatic refresh
- [ ] frontmatter tag or something that disables gathering from that file, probably automatically exclude files from popular plugins like excalidraw?
- [ ] more detailed usage guide
- [ ] fit the calendar better in the pane so that there is no scrolling
- [ ] customize startup view in calendar
- [ ] debugging options
